### ISSUE TITLE
Viewport meta tag

### ISSUE THREAD

**Issue by ghost** [zollipaul/Colmar-Academy#1]
https://github.com/zollipaul/Colmar-Academy/blob/master/index.html#L3-L8

Don't forget to include the viewport meta tag so that you can properly control the viewport's size and scale.

This is a _must_ for any mobile-optimized site.

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by zollipaul** [comment]
thanks, but I cannot remember that we covered it in any section throughout the course :)
