### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [zollipaul/Colmar-Academy#2]
https://github.com/zollipaul/Colmar-Academy/blob/master/index.html#L12-L33

Nice job making your markup more semantic by using tags like `header`, `nav` and `footer`. 👍 

This is much better than relying constantly on `div` tags, but see if you can incorporate some extra low-hanging fruit like `main` and `section`.

**Comment by zollipaul** [comment]
good feedback, thx!
