### ISSUE TITLE
Hover/interactive styling

### ISSUE THREAD

**Issue by ghost** [zollipaul/Colmar-Academy#5]
Awesome job using the various hover effects across your links, icons, and buttons to give your site that extra interactive feeling 👍 

Consider doing the same throughout the rest of your website like the "Fisma" and "Our Guest Lecture" sections so that their background color is not applied statically, but rather when the user hovers over the individual link.

Even if these links don't actually lead anywhere, it's important to have this sense of interaction for a modern site.

**Comment by zollipaul** [comment]
good idea. However, I thought that the grey background-color of guest-lecture and fisma should be static.
